### ISSUE TITLE
Installation and running

### ISSUE THREAD

**Issue by sefeoglu** [nlp-tlp/redcoat#31]
Hello, 

I tried to install and run your tool, but I got the message "Error: ENOENT: no such file or directory, stat '/Users/../redcoat/tagging_interface/build/index.html'".
index.html does not exist.
Could you help me in solving this problem?
I am running it on MacOS.

Thanks in advance.

Best regards,
Sefika

**Comment by sefeoglu** [comment]
Hi @Michael-Stewart-Webdev, 
The screen when I installed and start it is here:
<img width="1382" alt="Screenshot 2023-03-31 at 13 49 04" src="https://user-images.githubusercontent.com/4726002/229113014-c9a21118-2810-4ba1-ae10-4fae26c93721.png">

Could you help me in its installation?
Thanks.


Best.

**Comment by IvanDePivan** [comment]
I had the same issue but got it working by doing the following (on windows, some things may be OS specific):

1.  Update the connection string db_config.js to point to 127.0.0.1 instead of localhost
2. Run `mongod`
3. run `npm run start` in the top level folder
4. run `npm run start --openssl-legacy-provider` in the tagging_interface folder

**Comment by sefeoglu** [comment]
Thanks for the reply.
